### ISSUE TITLE
Add download button/link for generated merged file

### ISSUE THREAD

**Issue by stevieflow** [pwyf/iati-activity-merger#4]
When I click Generate - take me to a page/confirmation screen that has a Download button or link.

Avoid the current workflow whereby the data is generated on the fly

Note - an important use case here might be users that want to "save link as" and select a local directory, and/or a user that wants to wget the data.

I understand that this would in turn mean a) leaving merged files on the server for X days b) generating unique URLs for converted files (as we do with CoVE).  I wont create specific issues for those yet, however

**Comment by Lathrisk** [comment]
test version available at: https://iati-activity-merge.testing.opendataservices.uk0.bigv.io/
