### ISSUE TITLE
Provide a summary box after merging

### ISSUE THREAD

**Issue by stevieflow** [pwyf/iati-activity-merger#6]
After merging, provide a summary box to give the following information:

- DareTime of upload
- Number of files uploaded
- Activity count in merged file
- Name of the uploaded files

We have something similar in IATI CoVE

![IATI CoVE](https://user-images.githubusercontent.com/1209944/69826207-22bce880-120a-11ea-9273-d8e9d1676132.png)

Note - the "Convert to Spreadsheet" button in CoVE (when uploading XML) coudl be "Download merged file" in this application - see also #4

**Comment by Lathrisk** [comment]
test version available at: https://iati-activity-merge.testing.opendataservices.uk0.bigv.io/
