### ISSUE TITLE
Provide a Merge new files button

### ISSUE THREAD

**Issue by stevieflow** [pwyf/iati-activity-merger#8]
After merging files, it's not obvious where/how to restart the process

Add a button to do this - similar to how we do this with CoVE

![IATI CoVE (1)](https://user-images.githubusercontent.com/1209944/69917991-893d4300-1464-11ea-9757-4cad55f6a3cd.png)

**Comment by Lathrisk** [comment]
test version available at: https://iati-activity-merge.testing.opendataservices.uk0.bigv.io/
