### ISSUE TITLE
It's not possible to expand / collapse / all boxes

### ISSUE THREAD

**Issue by stevieflow** [pwyf/iati-activity-merger#9]
Once merged, you get the summary box and download button (as per #4 - thanks) 

One slight quirk is that you can open/collapse the two boxes (upload / download) - you can only open one in turn.  

![Data Quality Tester](https://user-images.githubusercontent.com/1209944/69918030-f18c2480-1464-11ea-9d2c-88c09a600023.png)

Provide a means to collapse / open all - as per CoVE

![IATI CoVE (1)](https://user-images.githubusercontent.com/1209944/69918032-fa7cf600-1464-11ea-8082-a7d6c9c56d19.png)

**Comment by Lathrisk** [comment]
test version available at: https://iati-activity-merge.testing.opendataservices.uk0.bigv.io/
